import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { createClient } from "@/supabase/server";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function PublicLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const supabase = await createClient();
	const { data, error } = await supabase.auth.getUser();

	if (error) {
		console.error(error);
	}

	if (data?.user) {
		redirect("/");
	}

	return (
		<div className="mx-auto w-full max-w-7xl sm:px-6 lg:px-8">{children}</div>
	);
}
